version: '3.7'
services:

  codecarbon_front:
    build:
      context: ./docker/keycloak/dashapp
      dockerfile: front.dockerfile
    ports:
      - 5081:5006
    volumes:
      - ./docker/keycloak/dashapp:/opt/codecarbon-front
  # codecarbon_package:
  #   build:
  #     context: ./codecarbon/
  #     dockerfile: ./docker/Dockerfile
  #   networks:
  #     - codecarbon_net
  #   volumes:
  #     - ./codecarbon:/opt/codecarbon
  #   depends_on:
  #     - codecarbon_api
  #   restart: unless-stopped
  nginx:
      image: nginx
      ports:
        - 8081:80
      volumes:
        - ./docker/keycloak/myapp:/usr/share/nginx/html

  carbonserver:
    build:
      context: ./carbonserver/
      dockerfile: ./docker/Dockerfile
    #command: cd /carbonserver/carbonserver/database && python3 -m alembic upgrade head && cd ../.. && uvicorn --reload main:app --host 0.0.0.0
    volumes:
      - ./carbonserver:/carbonserver
      # Avoid problems with local tox
      - /carbonserver/.tox
    ports:
      - 8008:8000
    environment:
      # DATABASE_URL: sqlite:///./code_carbon.db
      CODECARBON_LOG_LEVEL: DEBUG
      DATABASE_URL: postgresql://${DATABASE_USER:-codecarbon-user}:${DATABASE_PASS:-supersecret}@postgres/${DATABASE_NAME:-codecarbon_db}
    networks:
      - codecarbon_net

  postgres_keycloak:
    container_name: postgres_codecarbon_keycloak
    environment:
      HOSTNAME: postgres_codecarbon_keycloak
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: keycloak_pwd
      POSTGRES_USER: keycloak-user
    image: postgres:12
    networks:
      - codecarbon_net
    ports:
    - 5484:5432
    restart: unless-stopped
  
  postgres:
    container_name: ${DATABASE_HOST:-postgres_codecarbon}
    environment:
      HOSTNAME: ${DATABASE_HOST:-postgres_codecarbon}
      POSTGRES_DB: ${DATABASE_NAME:-codecarbon_db}
      POSTGRES_PASSWORD: ${DATABASE_PASS:-supersecret}
      POSTGRES_USER: ${DATABASE_USER:-codecarbon-user}
    image: postgres:12
    networks:
      - codecarbon_net
    ports:
    - 5480:5432
    restart: unless-stopped
    volumes:
    - postgres_data:/var/lib/postgresql/data:rw


  keycloak:
    image: jboss/keycloak
    environment:
      #DB_VENDOR: POSTGRES
      #DB_ADDR: postgres_codecarbon
      #DB_PORT: 5484
      #DB_DATABASE: codecarbon_db
      #DB_USER: codecarbon-user
      #DB_SCHEMA: public
      #DB_PASSWORD: supersecret
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8084:8080
    volumes:
      - ./docker/keycloak/themes/Breizhcamp/:/opt/jboss/keycloak/themes/Breizhcamp/
      - ./docker/keycloak/providers:/opt/jboss/keycloak/providers
      - ./docker/keycloak/scripts:/opt/jboss/scripts/
      - ./docker/keycloak/deploy:/opt/jboss/keycloak/standalone/deployments
    depends_on:
      - postgres_keycloak
      - smtp4dev

  smtp4dev:
      image: rnwood/smtp4dev
      ports:
        - 13000:80

  pgadmin:
    container_name: pgadmin_codecarbon
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-test@test.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-test}
    volumes:
       - pgadmin:/root/.pgadmin
       - ./carbonserver/docker/pgpassfile:/pgadmin4/pgpassfile
       - ./carbonserver/docker/pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5080}:80"
    networks:
      - codecarbon_net
    restart: unless-stopped

volumes:
  postgres_data:
    name: postgres_codecarbon_data
  pgadmin:
    name: pgadmin_codecarbon_data

networks:
  codecarbon_net:
    name: codecarbon_network
