{% set version = "0.1.0" %}

package:
  name: code-carbon
  version: {{ version }}

source:
  path: .

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python>3.6
    - apscheduler
    - co2-tracker-utils
    - dash
    - dash-bootstrap-components
    - dataclasses
    - fire
    - pandas
    - requests

test:
  imports:
    - codecarbon
    - codecarbon.external
    - codecarbon.utils
    - codecarbon.viz

about:
  home: https://github.com/mlco2/code-carbon
  license: MIT
  summary: 'Emissions Tracker'
  description: |
    Emissions Tracker is a Python package for tracking the carbon emissions produced by various kinds of computer programs, from straightforward algorithms to deep neural networks.

    By taking into account your computing infrastructure, location, usage and running time, Emissions Tracker can provide an estimate of how much CO2 you produced, and give you some comparisons with common modes of transporation to give you an order of magnitude.
  dev_url: https://github.com/mlco2/code-carbon
  doc_url: https://pypi.python.org/TO-BE-DEFINED/code-carbon
  doc_source_url: https://github.com/mlco2/code-carbon/blob/master/README.md
